### ISSUE TITLE
Am I doing it right?

### ISSUE THREAD

**Issue by frankfrancois** [bang-olufsen/mozart-open-api#13]
Hi
For some reason multiroom does not work between my Beosound Level and my Theatre (which is paired with two Beolab 28's with wireless powerlink). I've tried to contact support but I keep getting generic answers from them. I've made this simple test program:

(1) Is the IP of my Level. I start the radio playing dr p4 (favourite 4) 
(2) Is the JID of my Theatre
(3) Is the expand result. It says "joined"
(4) Is the playback events which says that music is playing

BUT I DON'T HEAR ANY SOUND IN EITHER THEATRE NOR BEOLAB (the Level is playing P4 fine) 🤗  

* Am I doing something wrong? Could you please explain multiroom join vs expand (or link to some tech info)
* Do I have any way to trace why I don't hear sound? Can I see a log file somewhere?

Kind Regards
Frank

![mr](https://github.com/bang-olufsen/mozart-open-api/assets/151915865/681c20fb-eb80-4480-99cc-6e19b431043a)

By the way: This is what the phone app says after I run the program. When I slide the "Level slider" the volume goes up/down 👍. When I slide the "Theatre Slider" nothing happens - no sound at all

![Skærmbillede 2024-02-25 kl  13 09 51](https://github.com/bang-olufsen/mozart-open-api/assets/151915865/4e9e5432-a107-486f-a9a5-912942357be1)

**Comment by mj23000** [comment]
No you're not doing anything wrong. I've written a response in the HACS integration issue (https://github.com/bang-olufsen/bang_olufsen-hacs/issues/16).

**Comment by frankfrancois** [comment]
By the way. I just ran the program again. Everything looks ok, it expands and plays according to the events:

![run program](https://github.com/bang-olufsen/mozart-open-api/assets/151915865/e8701603-4669-4509-8e64-12a1aacf8eb8)

And it clearly tells me that the music is expanded to my Theatre:

![get result](https://github.com/bang-olufsen/mozart-open-api/assets/151915865/a4d2d228-42f2-471e-81c4-0cd7241138c7)

But there is no sound in my theatre? I'm not the type to give up - is there anywhere I can trace/debug this further? I reckon it is a SW issue on the official B&O platform.

Kind regards 
Frank

**Comment by frankfrancois** [comment]
I have been in contact with support. They say that my TP-Link Mesh network maybe cause this problem. I will try another router. It is not a api issue so I'll close it
