### ISSUE TITLE
Allow later pydantic releases

### ISSUE THREAD

**Issue by fabaff** [bang-olufsen/mozart-open-api#14]
The PyPI entry for `mozart-api` points to this [repo](https://pypi.org/project/mozart-api). Not sure if it's a mistake as there here is no source code...

Anyways the `pyproject.toml` files says `pydantic = "^1.10.5, <2"`. Could you please consider to allow later `pydantic`? This is an issue for some distributions (like Nixpkgs) as only `pydantic>2` is available. The constraint for <2 doesn't affect users which are using `venv`s or the Home Assistant integration.

Thanks

**Comment by mj23000** [comment]
Hi

Most of the code is auto-generated and was therefore not included (This was also meant to be a language-independent repo for the API). We've however had some requests for the source code to be available somewhere, so it is probably going to available here.

Currently the Python API was generated with pydantic v1 as there were some problems with Home Assistant as far as I can remember, but it seems that is no longer the case. We'll release an updated API client with support for pydantic v2 shortly.

Kind regards

**Comment by mj23000** [comment]
Here you go https://pypi.org/project/mozart-api/3.4.1.8.2/

**Comment by mj23000** [comment]
OK. Home Assistant does not allow pydantic v2. The 3.4.1.8.2 release will remain available, but we will unfortunately be switching back to pydantic v1 for future releases for now.
